channels:
  - conda-forge
dependencies:
  - python=3.10
  - zeromq
  - pyzmq
  - pyyaml
  - trollsift
  - configobj
  - netifaces
  - satpy
  - pyresample
  - pykdtree
  - trollimage
  - rasterio
  - pyorbital
  - gdal
  - h5py
  - h5netcdf
  - hdf5plugin
  - netcdf4
  - paramiko
  - scp
  - fsspec
  - dpath
  - toolz
  - configobj
  - shapely
  - donfig
  - pip
  - scipy
  - fasteners
  - numcodecs
  - asciitree
  - git
  - s3fs
  - pip:
    - posttroll
    - git+https://github.com/mraspaud/trollflow2.git@feature-cli